runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi-postgres-db'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: ')ndS)7)IvgU`yvaU'
  INSTANCE_CONNECTION_NAME: 'cryptic-genre-365612:europe-west3:strapi-postgres-instance'

beta_settings:
  cloud_sql_instances: 'cryptic-genre-365612:europe-west3:strapi-postgres-instance'
 