runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'db-strapi-sql'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'OO0p;/AG^V-%mi$}'
  INSTANCE_CONNECTION_NAME: 'cryptic-genre-365612:europe-west3:db-strapi-sql-instance'

beta_settings:
  cloud_sql_instances: 'cryptic-genre-365612:europe-west3:db-strapi-sql-instance'
 